// Seed vocabulary data for Word Quest
// This populates localStorage with initial word data for grades 7 and 8

const GRADE_7_WORDS = [
  // A words
  { word: "abandon", meaning: "放弃；抛弃", phonetic: "/əˈbændən/", example: "He abandoned his plan." },
  { word: "ability", meaning: "能力；才能", phonetic: "/əˈbɪləti/", example: "She has the ability to learn quickly." },
  { word: "absent", meaning: "缺席的；不在的", phonetic: "/ˈæbsənt/", example: "He was absent from school." },
  { word: "absorb", meaning: "吸收；吸引", phonetic: "/əbˈzɔːrb/", example: "Plants absorb water." },
  { word: "abstract", meaning: "抽象的", phonetic: "/ˈæbstrækt/", example: "It's an abstract concept." },
  { word: "accept", meaning: "接受；认可", phonetic: "/əkˈsept/", example: "Please accept my apology." },
  { word: "access", meaning: "通道；进入", phonetic: "/ˈækses/", example: "We have access to the internet." },
  { word: "accident", meaning: "事故；意外", phonetic: "/ˈæksɪdənt/", example: "There was a car accident." },
  { word: "achieve", meaning: "实现；达到", phonetic: "/əˈtʃiːv/", example: "She achieved her goal." },
  { word: "acid", meaning: "酸；酸的", phonetic: "/ˈæsɪd/", example: "Lemon juice contains acid." },
  { word: "acknowledge", meaning: "承认；确认", phonetic: "/əkˈnɒlɪdʒ/", example: "He acknowledged his mistake." },
  { word: "acquire", meaning: "获得；学到", phonetic: "/əˈkwaɪər/", example: "She acquired new skills." },
  // B words
  { word: "balance", meaning: "平衡；天平", phonetic: "/ˈbæləns/", example: "Keep your balance." },
  { word: "basic", meaning: "基本的；基础的", phonetic: "/ˈbeɪsɪk/", example: "Learn the basic rules." },
  { word: "battery", meaning: "电池", phonetic: "/ˈbætəri/", example: "The battery is low." },
  { word: "behavior", meaning: "行为；举止", phonetic: "/bɪˈheɪvjər/", example: "Good behavior is important." },
  { word: "believe", meaning: "相信；认为", phonetic: "/bɪˈliːv/", example: "I believe in you." },
  { word: "benefit", meaning: "好处；利益", phonetic: "/ˈbenɪfɪt/", example: "Exercise has many benefits." },
  { word: "beyond", meaning: "超出；在…之外", phonetic: "/bɪˈjɒnd/", example: "It's beyond my understanding." },
  { word: "billion", meaning: "十亿", phonetic: "/ˈbɪljən/", example: "There are 8 billion people." },
  { word: "blame", meaning: "责备；归咎于", phonetic: "/bleɪm/", example: "Don't blame others." },
  { word: "block", meaning: "阻挡；街区", phonetic: "/blɒk/", example: "The road was blocked." },
  // C words
  { word: "calculate", meaning: "计算", phonetic: "/ˈkælkjuleɪt/", example: "Calculate the total cost." },
  { word: "campaign", meaning: "运动；活动", phonetic: "/kæmˈpeɪn/", example: "An election campaign." },
  { word: "capable", meaning: "有能力的", phonetic: "/ˈkeɪpəbl/", example: "She is capable of leading." },
  { word: "capture", meaning: "捕获；俘获", phonetic: "/ˈkæptʃər/", example: "They captured the moment." },
  { word: "carbon", meaning: "碳", phonetic: "/ˈkɑːrbən/", example: "Reduce carbon emissions." },
  { word: "career", meaning: "职业；生涯", phonetic: "/kəˈrɪər/", example: "She has a great career." },
  { word: "category", meaning: "类别；范畴", phonetic: "/ˈkætəɡəri/", example: "Sort items by category." },
  { word: "celebrate", meaning: "庆祝", phonetic: "/ˈselɪbreɪt/", example: "Let's celebrate!" },
  { word: "challenge", meaning: "挑战", phonetic: "/ˈtʃælɪndʒ/", example: "Accept the challenge." },
  { word: "chapter", meaning: "章节", phonetic: "/ˈtʃæptər/", example: "Read chapter one." },
  { word: "character", meaning: "性格；角色", phonetic: "/ˈkærəktər/", example: "She has a strong character." },
  { word: "chemical", meaning: "化学的；化学品", phonetic: "/ˈkemɪkl/", example: "A chemical reaction." },
  // D words
  { word: "damage", meaning: "损害；破坏", phonetic: "/ˈdæmɪdʒ/", example: "The storm caused damage." },
  { word: "debate", meaning: "辩论；争论", phonetic: "/dɪˈbeɪt/", example: "They had a heated debate." },
  { word: "decade", meaning: "十年", phonetic: "/ˈdekeɪd/", example: "Over the last decade." },
  { word: "decision", meaning: "决定；决策", phonetic: "/dɪˈsɪʒn/", example: "Make a decision." },
  { word: "declare", meaning: "宣布；声明", phonetic: "/dɪˈkleər/", example: "He declared independence." },
  { word: "decline", meaning: "下降；拒绝", phonetic: "/dɪˈklaɪn/", example: "Sales declined this year." },
  { word: "defeat", meaning: "击败；战胜", phonetic: "/dɪˈfiːt/", example: "They defeated the enemy." },
  { word: "define", meaning: "定义；解释", phonetic: "/dɪˈfaɪn/", example: "Define the term." },
  { word: "deliver", meaning: "递送；交付", phonetic: "/dɪˈlɪvər/", example: "Deliver the package." },
  { word: "demand", meaning: "要求；需求", phonetic: "/dɪˈmænd/", example: "Supply and demand." },
  { word: "demonstrate", meaning: "证明；演示", phonetic: "/ˈdemənstreɪt/", example: "Demonstrate your skills." },
  { word: "depend", meaning: "依赖；取决于", phonetic: "/dɪˈpend/", example: "It depends on you." },
  // E words
  { word: "economy", meaning: "经济", phonetic: "/ɪˈkɒnəmi/", example: "The global economy." },
  { word: "educate", meaning: "教育", phonetic: "/ˈedʒukeɪt/", example: "Educate the children." },
  { word: "effect", meaning: "效果；影响", phonetic: "/ɪˈfekt/", example: "Side effects of medicine." },
  { word: "efficient", meaning: "高效的", phonetic: "/ɪˈfɪʃnt/", example: "An efficient system." },
  { word: "eliminate", meaning: "消除；淘汰", phonetic: "/ɪˈlɪmɪneɪt/", example: "Eliminate the risk." },
  { word: "emerge", meaning: "出现；浮现", phonetic: "/ɪˈmɜːrdʒ/", example: "New evidence emerged." },
  { word: "emotion", meaning: "情感；情绪", phonetic: "/ɪˈmoʊʃn/", example: "Express your emotions." },
  { word: "emphasis", meaning: "强调；重点", phonetic: "/ˈemfəsɪs/", example: "Put emphasis on quality." },
  { word: "enable", meaning: "使能够", phonetic: "/ɪˈneɪbl/", example: "Technology enables us." },
  { word: "encounter", meaning: "遇到；邂逅", phonetic: "/ɪnˈkaʊntər/", example: "We encountered a problem." },
  // F words
  { word: "factor", meaning: "因素；要素", phonetic: "/ˈfæktər/", example: "An important factor." },
  { word: "failure", meaning: "失败", phonetic: "/ˈfeɪljər/", example: "Learn from failure." },
  { word: "feature", meaning: "特征；特色", phonetic: "/ˈfiːtʃər/", example: "A key feature." },
  { word: "fiction", meaning: "小说；虚构", phonetic: "/ˈfɪkʃn/", example: "Science fiction." },
  { word: "finance", meaning: "财务；金融", phonetic: "/ˈfaɪnæns/", example: "Personal finance." },
  { word: "focus", meaning: "集中；焦点", phonetic: "/ˈfoʊkəs/", example: "Focus on your studies." },
  { word: "forecast", meaning: "预测；预报", phonetic: "/ˈfɔːrkæst/", example: "Weather forecast." },
  { word: "foundation", meaning: "基础；地基", phonetic: "/faʊnˈdeɪʃn/", example: "Build a strong foundation." },
  { word: "framework", meaning: "框架；结构", phonetic: "/ˈfreɪmwɜːrk/", example: "A legal framework." },
  { word: "function", meaning: "功能；作用", phonetic: "/ˈfʌŋkʃn/", example: "The main function." },
  // G words
  { word: "generate", meaning: "产生；生成", phonetic: "/ˈdʒenəreɪt/", example: "Generate electricity." },
  { word: "global", meaning: "全球的", phonetic: "/ˈɡloʊbl/", example: "Global warming." },
  { word: "govern", meaning: "统治；管理", phonetic: "/ˈɡʌvərn/", example: "Rules that govern society." },
  { word: "gradual", meaning: "逐渐的", phonetic: "/ˈɡrædʒuəl/", example: "A gradual change." },
  { word: "guarantee", meaning: "保证；担保", phonetic: "/ˌɡærənˈtiː/", example: "Money-back guarantee." },
  { word: "guidance", meaning: "指导；引导", phonetic: "/ˈɡaɪdns/", example: "Need some guidance." },
  // H words
  { word: "hardware", meaning: "硬件", phonetic: "/ˈhɑːrdwer/", example: "Computer hardware." },
  { word: "headline", meaning: "标题；头条", phonetic: "/ˈhedlaɪn/", example: "The headline news." },
  { word: "heritage", meaning: "遗产；传统", phonetic: "/ˈherɪtɪdʒ/", example: "Cultural heritage." },
  { word: "highlight", meaning: "突出；亮点", phonetic: "/ˈhaɪlaɪt/", example: "The highlight of the trip." },
  { word: "horizon", meaning: "地平线；视野", phonetic: "/həˈraɪzn/", example: "On the horizon." },
  { word: "humble", meaning: "谦虚的", phonetic: "/ˈhʌmbl/", example: "Stay humble." },
  // I words
  { word: "identity", meaning: "身份；特性", phonetic: "/aɪˈdentəti/", example: "Prove your identity." },
  { word: "ignore", meaning: "忽视；不理", phonetic: "/ɪɡˈnɔːr/", example: "Don't ignore the warning." },
  { word: "illustrate", meaning: "说明；图解", phonetic: "/ˈɪləstreɪt/", example: "Illustrate the point." },
  { word: "imagine", meaning: "想象", phonetic: "/ɪˈmædʒɪn/", example: "Imagine the future." },
  { word: "impact", meaning: "影响；冲击", phonetic: "/ˈɪmpækt/", example: "A huge impact." },
  { word: "implement", meaning: "实施；执行", phonetic: "/ˈɪmplɪment/", example: "Implement the plan." },
  { word: "import", meaning: "进口；导入", phonetic: "/ˈɪmpɔːrt/", example: "Import goods." },
  { word: "impose", meaning: "强加；征收", phonetic: "/ɪmˈpoʊz/", example: "Impose a fine." },
  { word: "improve", meaning: "改善；提高", phonetic: "/ɪmˈpruːv/", example: "Improve your English." },
  { word: "income", meaning: "收入；所得", phonetic: "/ˈɪnkʌm/", example: "A steady income." },
  // J words
  { word: "journey", meaning: "旅程；旅行", phonetic: "/ˈdʒɜːrni/", example: "A long journey." },
  { word: "justice", meaning: "正义；公正", phonetic: "/ˈdʒʌstɪs/", example: "Fight for justice." },
  { word: "justify", meaning: "证明…有理", phonetic: "/ˈdʒʌstɪfaɪ/", example: "Justify your answer." },
  // K words
  { word: "keen", meaning: "热切的；敏锐的", phonetic: "/kiːn/", example: "She's keen to learn." },
  { word: "kernel", meaning: "核心；要点", phonetic: "/ˈkɜːrnl/", example: "The kernel of truth." },
  // L words
  { word: "launch", meaning: "发射；启动", phonetic: "/lɔːntʃ/", example: "Launch a rocket." },
  { word: "layer", meaning: "层；层次", phonetic: "/ˈleɪər/", example: "A layer of paint." },
  { word: "legacy", meaning: "遗产；遗留", phonetic: "/ˈleɡəsi/", example: "His lasting legacy." },
  { word: "leisure", meaning: "休闲；空闲", phonetic: "/ˈleʒər/", example: "Leisure time." },
  { word: "liberal", meaning: "自由的；开明的", phonetic: "/ˈlɪbərəl/", example: "Liberal views." },
  // M words
  { word: "maintain", meaning: "维持；保养", phonetic: "/meɪnˈteɪn/", example: "Maintain your health." },
  { word: "major", meaning: "主要的；重大的", phonetic: "/ˈmeɪdʒər/", example: "A major decision." },
  { word: "manage", meaning: "管理；经营", phonetic: "/ˈmænɪdʒ/", example: "Manage your time." },
  { word: "manufacture", meaning: "制造；生产", phonetic: "/ˌmænjuˈfæktʃər/", example: "Manufacture goods." },
  { word: "massive", meaning: "巨大的；大量的", phonetic: "/ˈmæsɪv/", example: "A massive building." },
  { word: "mental", meaning: "精神的；心理的", phonetic: "/ˈmentl/", example: "Mental health." },
  { word: "method", meaning: "方法；方式", phonetic: "/ˈmeθəd/", example: "A new method." },
  { word: "migrate", meaning: "迁移；移民", phonetic: "/ˈmaɪɡreɪt/", example: "Birds migrate south." },
  { word: "military", meaning: "军事的", phonetic: "/ˈmɪlɪteri/", example: "Military service." },
  { word: "minimum", meaning: "最小值；最低限度", phonetic: "/ˈmɪnɪməm/", example: "The minimum age." },
  // N words
  { word: "negative", meaning: "消极的；否定的", phonetic: "/ˈneɡətɪv/", example: "A negative result." },
  { word: "negotiate", meaning: "谈判；协商", phonetic: "/nɪˈɡoʊʃieɪt/", example: "Negotiate a deal." },
  { word: "network", meaning: "网络；关系网", phonetic: "/ˈnetwɜːrk/", example: "A social network." },
  { word: "neutral", meaning: "中立的；中性的", phonetic: "/ˈnjuːtrəl/", example: "Stay neutral." },
  { word: "nuclear", meaning: "核的；核能的", phonetic: "/ˈnjuːkliər/", example: "Nuclear energy." },
  // O words
  { word: "obvious", meaning: "明显的", phonetic: "/ˈɒbviəs/", example: "It's obvious." },
  { word: "occur", meaning: "发生；出现", phonetic: "/əˈkɜːr/", example: "Accidents occur." },
  { word: "operate", meaning: "操作；运营", phonetic: "/ˈɒpəreɪt/", example: "Operate the machine." },
  { word: "oppose", meaning: "反对", phonetic: "/əˈpoʊz/", example: "Oppose the plan." },
  { word: "organize", meaning: "组织；安排", phonetic: "/ˈɔːrɡənaɪz/", example: "Organize an event." },
  { word: "origin", meaning: "起源；出身", phonetic: "/ˈɒrɪdʒɪn/", example: "The origin of life." },
  { word: "outcome", meaning: "结果；成果", phonetic: "/ˈaʊtkʌm/", example: "A positive outcome." },
  { word: "overcome", meaning: "克服；战胜", phonetic: "/ˌoʊvərˈkʌm/", example: "Overcome difficulties." },
  // P words
  { word: "participate", meaning: "参加；参与", phonetic: "/pɑːrˈtɪsɪpeɪt/", example: "Participate in the game." },
  { word: "passage", meaning: "通道；段落", phonetic: "/ˈpæsɪdʒ/", example: "Read the passage." },
  { word: "pattern", meaning: "模式；图案", phonetic: "/ˈpætərn/", example: "A behavior pattern." },
  { word: "penalty", meaning: "处罚；罚款", phonetic: "/ˈpenəlti/", example: "Pay a penalty." },
  { word: "percent", meaning: "百分之…", phonetic: "/pərˈsent/", example: "Fifty percent." },
  { word: "permit", meaning: "允许；许可", phonetic: "/pərˈmɪt/", example: "Permit me to explain." },
  { word: "perspective", meaning: "视角；观点", phonetic: "/pərˈspektɪv/", example: "A different perspective." },
  { word: "philosophy", meaning: "哲学", phonetic: "/fɪˈlɒsəfi/", example: "Study philosophy." },
  { word: "physical", meaning: "身体的；物理的", phonetic: "/ˈfɪzɪkl/", example: "Physical exercise." },
  { word: "policy", meaning: "政策；方针", phonetic: "/ˈpɒləsi/", example: "Government policy." },
  // Q words
  { word: "qualify", meaning: "取得资格；合格", phonetic: "/ˈkwɒlɪfaɪ/", example: "Qualify for the finals." },
  { word: "quantity", meaning: "数量", phonetic: "/ˈkwɒntəti/", example: "A large quantity." },
  // R words
  { word: "range", meaning: "范围；系列", phonetic: "/reɪndʒ/", example: "A wide range of products." },
  { word: "recognize", meaning: "认出；承认", phonetic: "/ˈrekəɡnaɪz/", example: "I recognized her voice." },
  { word: "recommend", meaning: "推荐；建议", phonetic: "/ˌrekəˈmend/", example: "I recommend this book." },
  { word: "recover", meaning: "恢复；复原", phonetic: "/rɪˈkʌvər/", example: "Recover from illness." },
  { word: "reduce", meaning: "减少；降低", phonetic: "/rɪˈdjuːs/", example: "Reduce waste." },
  { word: "reflect", meaning: "反射；反思", phonetic: "/rɪˈflekt/", example: "Reflect on your actions." },
  { word: "reform", meaning: "改革；改进", phonetic: "/rɪˈfɔːrm/", example: "Education reform." },
  { word: "region", meaning: "地区；区域", phonetic: "/ˈriːdʒən/", example: "The tropical region." },
  { word: "regulate", meaning: "调节；管制", phonetic: "/ˈreɡjuleɪt/", example: "Regulate the temperature." },
  { word: "reinforce", meaning: "加强；增援", phonetic: "/ˌriːɪnˈfɔːrs/", example: "Reinforce the structure." },
  // S words
  { word: "sacrifice", meaning: "牺牲；献祭", phonetic: "/ˈsækrɪfaɪs/", example: "Make a sacrifice." },
  { word: "schedule", meaning: "日程；安排", phonetic: "/ˈʃedjuːl/", example: "Check the schedule." },
  { word: "secure", meaning: "安全的；确保", phonetic: "/sɪˈkjʊər/", example: "A secure password." },
  { word: "sequence", meaning: "顺序；序列", phonetic: "/ˈsiːkwəns/", example: "In sequence." },
  { word: "significant", meaning: "重大的；有意义的", phonetic: "/sɪɡˈnɪfɪkənt/", example: "A significant change." },
  { word: "strategy", meaning: "策略；战略", phonetic: "/ˈstrætədʒi/", example: "A marketing strategy." },
  { word: "structure", meaning: "结构；构造", phonetic: "/ˈstrʌktʃər/", example: "The structure of a cell." },
  { word: "sufficient", meaning: "足够的；充分的", phonetic: "/səˈfɪʃnt/", example: "Sufficient evidence." },
  { word: "summarize", meaning: "总结；概述", phonetic: "/ˈsʌməraɪz/", example: "Summarize the article." },
  { word: "survive", meaning: "幸存；存活", phonetic: "/sərˈvaɪv/", example: "Survive in the wild." },
  // T words
  { word: "target", meaning: "目标；靶子", phonetic: "/ˈtɑːrɡɪt/", example: "Hit the target." },
  { word: "temporary", meaning: "暂时的", phonetic: "/ˈtempəreri/", example: "A temporary solution." },
  { word: "theory", meaning: "理论；学说", phonetic: "/ˈθɪəri/", example: "The theory of evolution." },
  { word: "threaten", meaning: "威胁；恐吓", phonetic: "/ˈθretn/", example: "Don't threaten me." },
  { word: "tradition", meaning: "传统；惯例", phonetic: "/trəˈdɪʃn/", example: "A family tradition." },
  { word: "transfer", meaning: "转移；调动", phonetic: "/trænsˈfɜːr/", example: "Transfer money." },
  { word: "transform", meaning: "转变；改造", phonetic: "/trænsˈfɔːrm/", example: "Transform the city." },
  { word: "transport", meaning: "运输；交通", phonetic: "/ˈtrænspɔːrt/", example: "Public transport." },
  { word: "trend", meaning: "趋势；潮流", phonetic: "/trend/", example: "A new trend." },
  { word: "triumph", meaning: "胜利；成功", phonetic: "/ˈtraɪʌmf/", example: "A moment of triumph." },
  // U words
  { word: "ultimate", meaning: "最终的；终极的", phonetic: "/ˈʌltɪmət/", example: "The ultimate goal." },
  { word: "undergo", meaning: "经历；遭受", phonetic: "/ˌʌndərˈɡoʊ/", example: "Undergo surgery." },
  { word: "unique", meaning: "独特的；唯一的", phonetic: "/juˈniːk/", example: "A unique opportunity." },
  { word: "universe", meaning: "宇宙", phonetic: "/ˈjuːnɪvɜːrs/", example: "The vast universe." },
  { word: "urban", meaning: "城市的", phonetic: "/ˈɜːrbən/", example: "Urban development." },
  // V words
  { word: "valuable", meaning: "有价值的；贵重的", phonetic: "/ˈvæljuəbl/", example: "Valuable information." },
  { word: "variety", meaning: "多样性；种类", phonetic: "/vəˈraɪəti/", example: "A variety of options." },
  { word: "vehicle", meaning: "车辆；交通工具", phonetic: "/ˈviːɪkl/", example: "Electric vehicles." },
  { word: "version", meaning: "版本；说法", phonetic: "/ˈvɜːrʒn/", example: "The latest version." },
  { word: "virtual", meaning: "虚拟的", phonetic: "/ˈvɜːrtʃuəl/", example: "Virtual reality." },
  { word: "visible", meaning: "可见的；明显的", phonetic: "/ˈvɪzəbl/", example: "Clearly visible." },
  { word: "vision", meaning: "视力；愿景", phonetic: "/ˈvɪʒn/", example: "A vision for the future." },
  { word: "volume", meaning: "体积；音量；卷", phonetic: "/ˈvɒljuːm/", example: "Turn up the volume." },
  { word: "volunteer", meaning: "志愿者", phonetic: "/ˌvɒlənˈtɪər/", example: "Volunteer your time." },
  // W words
  { word: "welfare", meaning: "福利；幸福", phonetic: "/ˈwelfer/", example: "Social welfare." },
  { word: "widespread", meaning: "广泛的；普遍的", phonetic: "/ˈwaɪdspred/", example: "Widespread support." },
  { word: "wisdom", meaning: "智慧", phonetic: "/ˈwɪzdəm/", example: "Words of wisdom." },
  { word: "withdraw", meaning: "撤回；取款", phonetic: "/wɪðˈdrɔː/", example: "Withdraw money." },
  { word: "witness", meaning: "目击者；证人", phonetic: "/ˈwɪtnəs/", example: "An eyewitness." },
];

export function seedWordsIfNeeded() {
  const existing = localStorage.getItem('wq_words');
  if (existing) {
    const parsed = JSON.parse(existing);
    if (parsed.length > 0) return; // Already seeded
  }

  const words = GRADE_7_WORDS.map((w, i) => ({
    id: crypto.randomUUID(),
    word: w.word,
    meaning: w.meaning,
    phonetic: w.phonetic,
    example: w.example,
    grade: 7,
    unit: Math.floor(i / 10) + 1,
    created_at: new Date().toISOString(),
  }));

  // Also create grade 8 words (duplicate with grade 8 for now)
  const grade8Words = GRADE_7_WORDS.slice(0, 80).map((w, i) => ({
    id: crypto.randomUUID(),
    word: w.word,
    meaning: w.meaning,
    phonetic: w.phonetic,
    example: w.example,
    grade: 8,
    unit: Math.floor(i / 10) + 1,
    created_at: new Date().toISOString(),
  }));

  localStorage.setItem('wq_words', JSON.stringify([...words, ...grade8Words]));
  console.log(`[SeedData] Seeded ${words.length + grade8Words.length} words`);
}
