UPDATE public.badges
SET description = CASE name
  WHEN '初出茅庐' THEN '注册账号并开启学习之旅'
  WHEN '初入江湖' THEN '注册账号并开启学习之旅'
  WHEN '初来乍到' THEN '注册账号并开启学习之旅'
  WHEN '新手上路' THEN '注册账号并开启学习之旅'
  WHEN '起步之星' THEN '注册账号并开启学习之旅'
  WHEN '词汇新秀' THEN '掌握 100 个英语单词'
  WHEN '词汇学徒' THEN '掌握 100 个英语单词'
  WHEN '学海无涯' THEN '掌握 100 个英语单词'
  WHEN '词海探险家' THEN '掌握 500 个英语单词'
  WHEN '词汇达人' THEN '掌握 500 个英语单词'
  WHEN '单词大师' THEN '掌握 1000 个英语单词'
  WHEN '词汇大师' THEN '掌握 1000 个英语单词'
  WHEN '博学多才' THEN '掌握 2000 个英语单词'
  WHEN '词汇宗师' THEN '掌握 2000 个英语单词'
  WHEN '首战告捷' THEN '赢得 1 场对战'
  WHEN '初战告捷' THEN '赢得 1 场对战'
  WHEN '常胜将军' THEN '赢得 50 场对战'
  WHEN '百战勇士' THEN '累计完成 100 场对战'
  WHEN '千胜传说' THEN '赢得 1000 场对战'
  WHEN '不败战神' THEN '赢得 100 场对战且胜率 ≥ 90%'
  WHEN '连胜新星' THEN '单局达成 3 连击'
  WHEN '闪电侠' THEN '单局达成 10 连击'
  WHEN 'Combo之王' THEN '单局达成 20 连击'
  WHEN '满分学霸' THEN '任意关卡获得 100 分'
  WHEN '完美主义' THEN '任意关卡获得 100 分'
  WHEN '完美主义者' THEN '任意关卡获得 100 分'
  WHEN '三星收割机' THEN '10 个关卡获得三星评价'
  WHEN '完美碾压' THEN '5 个关卡获得满分'
  WHEN '白银新秀' THEN '排位段位达到 白银 或以上'
  WHEN '黄金战士' THEN '排位段位达到 黄金 或以上'
  WHEN '铂金精英' THEN '排位段位达到 铂金 或以上'
  WHEN '钻石传说' THEN '排位段位达到 钻石 或以上'
  WHEN '王者荣耀' THEN '排位段位达到 钻石 或以上'
  WHEN '最强王者' THEN '排位段位达到 王者'
  WHEN '巅峰王者' THEN '排位段位达到 王者'
  WHEN '传奇玩家' THEN '排位段位达到 王者'
  WHEN '狄邦巅峰' THEN '排位段位达到 王者'
  WHEN '小有积蓄' THEN '拥有 100 狄邦豆'
  WHEN '财富新贵' THEN '拥有 1000 狄邦豆'
  WHEN '富甲一方' THEN '拥有 1000 狄邦豆'
  WHEN '金库守护' THEN '拥有 5000 狄邦豆'
  WHEN '财富传奇' THEN '拥有 10000 狄邦豆'
  WHEN '三日打卡' THEN '连续登录 3 天'
  WHEN '坚持不懈' THEN '连续登录 7 天'
  WHEN '月度达人' THEN '连续登录 30 天'
  WHEN '学霸之路' THEN '连续登录 30 天'
  WHEN '百日坚持' THEN '连续登录 100 天'
  WHEN '全年无休' THEN '连续登录 365 天'
  WHEN '经验丰富' THEN '账号等级达到 Lv.10'
  WHEN '升级达人' THEN '账号等级达到 Lv.20'
  WHEN '高手之路' THEN '账号等级达到 Lv.50'
  WHEN '数学启蒙' THEN '掌握 1 个数学单词'
  WHEN '数学新手' THEN '掌握 50 个数学单词'
  WHEN '数学达人' THEN '掌握 100 个数学单词'
  WHEN '数学大师' THEN '掌握全部数学单词'
  WHEN '科学启蒙' THEN '掌握 1 个科学单词'
  WHEN '科学新手' THEN '掌握 100 个科学单词'
  WHEN '科学探索者' THEN '掌握 300 个科学单词'
  WHEN '科学先锋' THEN '掌握 500 个科学单词'
  WHEN '科学大师' THEN '掌握全部科学单词'
  ELSE description
END;
