
-- SEED BADGES
INSERT INTO badges (name, description, icon, category, rarity) VALUES
('初来乍到', '首次登录游戏', 'Sprout', 'welcome', 'common'),
('新手上路', '完成第一个关卡', 'Star', 'welcome', 'common'),
('起步之星', '累计学习10个单词', 'Sparkles', 'welcome', 'common'),
('词汇学徒', '累计学习50个单词', 'BookOpen', 'learning', 'common'),
('词汇达人', '累计学习200个单词', 'BookOpenCheck', 'learning', 'rare'),
('词汇大师', '累计学习500个单词', 'Library', 'learning', 'epic'),
('词汇宗师', '累计学习1000个单词', 'GraduationCap', 'learning', 'legendary'),
('博学多才', '累计学习2000个单词', 'Crown', 'learning', 'mythology'),
('满分学霸', '任意关卡获得100%正确率', 'Target', 'learning', 'rare'),
('三星收割机', '获得10个三星关卡', 'Star', 'learning', 'epic'),
('初战告捷', '赢得第一场对战', 'Sword', 'battle', 'common'),
('百战勇士', '累计参加100场对战', 'Swords', 'battle', 'rare'),
('常胜将军', '累计赢得50场对战', 'Trophy', 'battle', 'epic'),
('不败战神', '累计赢得200场对战', 'Crown', 'battle', 'legendary'),
('千胜传说', '累计赢得1000场对战', 'Medal', 'battle', 'mythology'),
('完美碾压', '对战中以10-0获胜', 'Zap', 'battle', 'epic'),
('逆风翻盘', '在0-5落后时最终获胜', 'TrendingUp', 'battle', 'legendary'),
('三日打卡', '连续登录3天', 'Flame', 'streak', 'common'),
('周末战士', '连续登录7天', 'Flame', 'streak', 'rare'),
('月度达人', '连续登录30天', 'Flame', 'streak', 'epic'),
('百日坚持', '连续登录100天', 'Flame', 'streak', 'legendary'),
('全年无休', '连续登录365天', 'Flame', 'streak', 'mythology'),
('升级达人', '达到等级10', 'TrendingUp', 'achievement', 'common'),
('经验丰富', '达到等级25', 'TrendingUp', 'achievement', 'rare'),
('高手之路', '达到等级50', 'Award', 'achievement', 'epic'),
('传奇玩家', '达到等级100', 'Crown', 'achievement', 'legendary'),
('最强王者', '达到等级200', 'Gem', 'achievement', 'mythology'),
('白银新秀', '排位赛达到白银段位', 'Medal', 'ranked', 'common'),
('黄金战士', '排位赛达到黄金段位', 'Medal', 'ranked', 'rare'),
('铂金精英', '排位赛达到铂金段位', 'Trophy', 'ranked', 'epic'),
('钻石传说', '排位赛达到钻石段位', 'Gem', 'ranked', 'legendary'),
('巅峰王者', '排位赛达到王者段位', 'Crown', 'ranked', 'mythology'),
('小有积蓄', '累计获得1000金币', 'Coins', 'wealth', 'common'),
('富甲一方', '累计获得10000金币', 'Coins', 'wealth', 'rare'),
('金库守护', '累计获得50000金币', 'Coins', 'wealth', 'epic'),
('财富传奇', '累计获得200000金币', 'Coins', 'wealth', 'legendary'),
('挑战先锋', '首次参加班级挑战赛', 'Compass', 'challenge', 'common'),
('班级之光', '班级挑战赛排名前3', 'Star', 'challenge', 'rare'),
('年级之巅', '年级挑战赛排名第1', 'Crown', 'challenge', 'legendary'),
('社交蝴蝶', '添加10个好友', 'Users', 'special', 'rare'),
('团队精神', '加入一个战队', 'HandMetal', 'special', 'common'),
('爱心天使', '累计赠送100金币给好友', 'Heart', 'special', 'rare'),
('夜猫子', '在凌晨2-4点完成一个关卡', '🦉', 'hidden', 'hidden'),
('闪电侠', '对战中在3秒内答对一题', '⚡', 'hidden', 'hidden'),
('完美主义', '连续答对100道题', '💎', 'hidden', 'hidden'),
('彩蛋猎人', '发现一个隐藏功能', '🥚', 'hidden', 'hidden'),
('Combo之王', '单局达到50连击', '🔥', 'hidden', 'hidden');

-- SEED NAME CARDS
INSERT INTO name_cards (name, description, background_gradient, icon, category, rarity) VALUES
('晨曦微光', '清晨的第一缕阳光', 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', 'Sparkles', 'achievement', 'common'),
('碧海蓝天', '无边的蔚蓝', 'linear-gradient(135deg, #2196F3 0%, #00BCD4 100%)', 'Compass', 'achievement', 'common'),
('春意盎然', '万物复苏的季节', 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)', 'Sprout', 'achievement', 'common'),
('落日余晖', '夕阳无限好', 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', 'Star', 'achievement', 'common'),
('静谧星空', '繁星点点的夜空', 'linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)', 'Star', 'achievement', 'common'),
('烈焰战魂', '对战场上的火焰之心', 'linear-gradient(135deg, #f12711 0%, #f5af19 100%)', 'Flame', 'battle', 'rare'),
('知识殿堂', '学海无涯苦作舟', 'linear-gradient(135deg, #4568DC 0%, #B06AB3 100%)', 'BookOpen', 'learning', 'rare'),
('极光之舞', '北极光的绚丽之美', 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', 'Sparkles', 'achievement', 'rare'),
('紫电惊雷', '雷霆万钧之势', 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)', 'Zap', 'battle', 'rare'),
('铁壁铜墙', '坚不可摧的防线', 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', 'Medal', 'ranked', 'rare'),
('星辰大海', '征途是星辰和大海', 'linear-gradient(135deg, #0F2027 0%, #203A43 50%, #2C5364 100%)', 'Compass', 'achievement', 'epic'),
('龙吟虎啸', '王者之气', 'linear-gradient(135deg, #c31432 0%, #240b36 100%)', 'Swords', 'battle', 'epic'),
('凤舞九天', '涅槃重生的传说', 'linear-gradient(135deg, #f953c6 0%, #b91d73 100%)', 'Crown', 'achievement', 'epic'),
('冰封王座', '寒冰之力统御一切', 'linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%)', 'Gem', 'ranked', 'epic'),
('万世之冠', '万古流芳的荣耀', 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)', 'Crown', 'ranked', 'legendary'),
('学神降临', '学习之巅的传说', 'linear-gradient(135deg, #c471f5 0%, #fa71cd 100%)', 'GraduationCap', 'learning', 'legendary'),
('战神无双', '千军万马中无人可挡', 'linear-gradient(135deg, #b91d73 0%, #f953c6 50%, #f7971e 100%)', 'Swords', 'battle', 'legendary'),
('鸿蒙初开', '开天辟地的至高存在', 'linear-gradient(135deg, #ff0000 0%, #dc143c 30%, #8b0000 60%, #ff4500 100%)', 'Crown', 'special', 'mythology'),
('诸神黄昏', '诸神陨落之时', 'linear-gradient(135deg, #8b0000 0%, #2f0000 50%, #ff6347 100%)', 'Gem', 'special', 'mythology'),
('彩虹使者', '发现隐藏的彩虹', 'linear-gradient(135deg, #f43f5e 0%, #f59e0b 25%, #10b981 50%, #06b6d4 75%, #8b5cf6 100%)', '🌈', 'hidden', 'hidden'),
('时空旅人', '穿越时空的神秘旅者', 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 30%, #06b6d4 60%, #10b981 100%)', '🕐', 'hidden', 'hidden');
