// This file is automatically generated. Do not edit it directly.
import { createClient, type SupportedStorage } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsfuyevlhamssomxqvwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZnV5ZXZsaGFtc3NvbXhxdndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MzI5OTYsImV4cCI6MjA5MDEwODk5Nn0.eXZHFLFAujZmZPZ3d7kqMKlwRctkSJuCGgHAOdW2mEw";

const memoryStorage = (): SupportedStorage => {
  const store = new Map<string, string>();

  return {
    getItem: (key) => store.get(key) ?? null,
    setItem: (key, value) => {
      store.set(key, value);
    },
    removeItem: (key) => {
      store.delete(key);
    },
  };
};

const getSafeStorage = (): SupportedStorage => {
  if (typeof window === 'undefined') return memoryStorage();

  try {
    const testKey = '__supabase_storage_test__';
    window.localStorage.setItem(testKey, testKey);
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch {
    return memoryStorage();
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});