// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsfuyevlhamssomxqvwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZnV5ZXZsaGFtc3NvbXhxdndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MzI5OTYsImV4cCI6MjA5MDEwODk5Nn0.eXZHFLFAujZmZPZ3d7kqMKlwRctkSJuCGgHAOdW2mEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});