// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhqvikfvalbwfkadqcsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocXZpa2Z2YWxid2ZrYWRxY3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NTA0NTQsImV4cCI6MjA4NzEyNjQ1NH0.lPhjvjbYljxVfZp2YJA1QSPYYT9PHr444TsY46-5OVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});